apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - prometheus-helmrepository.yaml
  - prometheus-helmrelease.yaml
  - loki-helmrepository.yaml
  - loki-helmrelease.yaml
  - promtail-helmrelease.yaml
  - grafana-helmrelease.yaml
  - grafana-ingress.yaml
  - grafana-dashboard-wordpress.yaml

