apiVersion: ENC[AES256_GCM,data:6uQ=,iv:O9K5uisGJez7N76h96Al2DZvzCGaWQTTHqfa00TI/CA=,tag:8V0uGcC/MaQ3Tz+zahm+KA==,type:str]
kind: ENC[AES256_GCM,data:8pwiA2Nw,iv:yTC6qMpk8wzdjwvWYsqhdR16J88AOxAP/DgZycQHjcI=,tag:XMrgM21YeHTwKYDYNcbdsg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GPwPLabLVAP/0mOP,iv:Xky+IaCJ8/8EqtyvAOWrsRcxJCuMSVTCS2BoVlvw2YE=,tag:oj1ICEv7f4AmBOqolZQCwg==,type:str]
    namespace: ENC[AES256_GCM,data:Yi5n0RyE3pWwjkszYpVAgQ==,iv:eO1MA/JPk1uHS7WR5gTQi9UYoiOR+MvTMuTsddehZCU=,tag:SStIjwhJgzRo2Ns2rnsEDw==,type:str]
type: ENC[AES256_GCM,data:V18EFc99,iv:qcfQjCBxfzb3ldXbxTw+7qua8ECAErkg5qcEamMuAK0=,tag:Y7Dy6sPKaM3dFXyUHSA9vw==,type:str]
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:OaMz/jXPGAIK21by,iv:SAAleNsX7nU08pkNoondrlEkrRpqdAmgh6mQ5sF+K/c=,tag:sXeYIYu7/MD2/gyqs6SGiA==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:6LIteTA7aB6x,iv:E/r7PjFOYnQwCiGOn5GiELztejOTKgrobUPqNtMiRoo=,tag:OPNBvDHyJu4bEJ+fjOaIQQ==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:h1sUo/rRhb6k,iv:f1fPLwYUIRuj877aYaivGQV4WF8ZrJpxfy1JFptgoTs=,tag:vWebg/7PhNA7RhdZN1hsUg==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:r3dunYl+29zQJ3kM5/+zaHo=,iv:elSSV7jSW5ylmTDkNqU3dyqGlD4Z6dxMvc6o4bLZ+PY=,tag:oFv76J56QCKniduK4HQXUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dusesg6w7m2e5g5jz84962edk250thms2hpczjjj2r93kdln4g5smts2hz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNzVpenpMZVpIQ09FNS9T
            ZEdPVXVRTzY5SjlXUldjVUhEMXVUZ0l2c1djCkpWQ1JyY0VKdmxGTGR2djNtT1Ji
            ZTdEa1JLUHZsdTNncFVOZy9Ib2lYTTQKLS0tIGlwTlJ5Z1paKzV0NHNWeFpJZ09s
            dW1BQ2Fla1loWXN0aG5WUGVFS0VveFkKpUWiaeM27cbYbpEBqvoZBFCyVRoEjog6
            tQVlbVjbHbzXdHS0plqRKxy/TU9eSlWI017zIHVUKTHvgyznjGlIsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T09:25:21Z"
    mac: ENC[AES256_GCM,data:WeJrbVR3VWqHW7hjLMmC1l3Bu4ZLjWyAH16doLW6reRRtA5fhjfodYaBcv+BTqTP6LOat6c5iLTGLBo/YPCHg7AUF5iwwhLmCLlQPg3coIx1CZN+Ajlyhwn7jR5OG+L6loAQUCQAmzGSyMI8hsj7HMJ2sPVprGMi9YAGKvxPVMo=,iv:7VEdRUUyDXmQn1uAmMYSAWNFRvbvk5qrmjMl8b8gNH0=,tag:SFHEbJ1tpRkPKfK/lbsdOg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1

