apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: wedevs-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/sorkerlimon/wedevs
  ref:
    branch: main
  secretRef:
    name: github-credentials

